MODEL_NAME = "FR_avg_return24_l3_gt_0_fr3_yr1"
MODEL_VERSION = 1
RISK_MODEL_NAME = "D_b_r3_decay_l15"
RECOVERY_MODEL_NAME = "avg_return24_l3_gt_0"
RISK_WINDOW = 15
RECOVERY_WINDOW = 3
MIN_PRIOR_VALUES = 10
WARMUP_DAYS = 30
